# fetch 함수와 비동기 실행

## 비동기 실행
* 비동기 실행: 특정 작업을 시작(리퀘스트 보내기)하고 완벽하게 다 처리(리스폰스를 받아서 처리)하기 전에, 실행 흐름이 바로 다음 코드로 넘어가고, 나중에 콜백이 실행되는 것
* fetch 함수는 비동기 실행이며 콜백을 파라미터로 바로 전달받는 게 아니라, fetch 함수가 리턴하는 어떤 객체의 then 메소드를 사용해서 콜백을 등록
* 비동기 실행이 동기 실행에 비해, 동일한 작업을 더 빠른 시간 내에 처리
``` javascript
console.log('Start!');

fetch('https://www.google.com')
  .then((response) => response.text())
  .then((result) => { console.log(result); });

console.log('End'); 
```
1. console.log('Start');
2. fetch 함수(리퀘스트 보내기 및 콜백 등록)
3. console.log('End');
4. 리스폰스가 오면 2. 에서 then 메소드로 등록해뒀던 콜백 실행(fetch 함수가 리퀘스트를 보내고, 서버의 리스폰스를 받게 되면 그때서야 콜백들이 순서대로 실행된다)

## 동기 실행
* 동기 실행: 한번 시작한 작업은 다 처리하고 나서야, 다음 코드로 넘어가는, 우리에게 익숙한 방식의 실행

# 비동기 실행 함수들

## setTimeout(콜백, 시간) 함수
```javascript
console.log('a');
setTimeout(() => { console.log('b'); }, 2000);
console.log('c');
```
* 이 콜백의 실행을, 두 번째 파라미터에 적힌 2000 밀리세컨즈(=2초) 뒤로 미룹

## setInterval(콜백, 시간) 함수
```javascript
console.log('a');
setInterval(() => { console.log('b'); }, 2000);
console.log('c');
```
* b를 출력하는 콜백이 2초 간격으로 계속 실행

## addEventListener(이벤트 이름, 콜백) 함수

# fetch 함수는 Promise 객체를 리턴합니다
* promise: 작업에 관한 '상태 정보'이며 fulfilled 상태(fetch 함수가 request를 보내고 response를 정상적으로 받았을 때)가 되면 작업 성공 결과를 갖게 되며 (콜백의 파라미터로 넘어간다) rejected 상태가 되면 작업 실패 정보를 갖게 된다
* then 메소드: promise가 fulfilled 상태가 되었을 때, 실행할 콜백 등록하며 다음 then은 이전 콜백의 리턴값을 파라미터로 받아 사용한다
<img width="766" alt="image" src="https://user-images.githubusercontent.com/88610333/182541735-9923bbce-415d-4089-bcd8-4540f917376c.png">

# Promise Chaining이란?
* promise chaining: then 메소드(promise 객체 리턴) 여러개 붙이는 것
<img width="766" alt="image" src="https://user-images.githubusercontent.com/88610333/182545501-402a527b-1ad5-4a87-9260-ecfff9e7cf88.png">
<img width="766" alt="image" src="https://user-images.githubusercontent.com/88610333/182545555-871f44d0-eb9f-457e-b93e-ba58d2bf60ac.png">
<img width="766" alt="image" src="https://user-images.githubusercontent.com/88610333/182545601-460a9a70-ae52-4fbd-aa3d-4c2048ca28f8.png">

# rejected 상태가 되면 실행할 콜백
* then 메소드의 2번째 파라미터로 넣으면 된다
* 작업 실패 정보가 파라미터로 넘어간다
```javascript
fetch('https://jsonplaceholder.typicode.commm/user')
  .then((responses) => responses.text(), (error) => {console.log(error);})
  .then((result) => {console.log(result);});
```
## catch 메소드
* catch: rejected 상태가 되면 실행할 콜백 등록하는 메소드
* 가장 마지막에 붙임으로써, 중간에 에러가 발생해서 어느 Promise 객체가 rejected 상태가 되더라도 항상 대처할 수 있다
* 단, 비록 에러가 발생했다고 해도 만약 실패한 작업 대신 다른 방법을 통해서 작업을 정상적으로 끝마칠 수 있는 상황이라면 catch 메소드를 중간에도 사용 
```javascript
fetch('https://jsonplaceholder.typicode.com,,/user')
  .then((responses) => responses.text())
  .catch((error) => {console.log(error);}); -> 사실 .then(undefined, (error) => {console.log(error);}) 와 동일하다(즉 then 메소드 변형)
```

# fulfilled/rejected 상관없이 항상 실행할 콜백
## finally 메소드
* 어떠한 경우에도 실행된다
* 보통 catch 메소드 뒤에 쓴다
```javascript
fetch('https://jsonplaceholder.typicode.com,,/user')
  .then((responses) => responses.text())
  .then((result) => {console.log(result);})
  .catch((error) => {console.log(error);})
  .finally(() => {console.logg('exit');});
```

# 직접 만들어보는 Promise 객체
```javascript
const p = new Promise((resolve, reject) => {
  setTimeout(() => {resolve('success');}, 2000);
});
p.then((result) => {console.log(result);});
```
```javascript
const p = new Promise((resolve, reject) => {
  setTimeout(() => {reject new Error('fail');}, 2000);
});
p.error((result) => {console.log(error);});
```

# Promisfy
* promisfy: 전통적인 형식의 비동기 실행 함수 중 콜백을 한번만 실행하는 함수를 Promise 객체로 감싸서 그 Promise 객체를 리턴하는 형식으로 만드는 작업
* 기존의 비동기 실행 함수(여기서는 setTimeout)의 콜백이 리턴하는 값을 Promise Chain에서 사용하고 싶다면, 해당 함수를 감싸서 Promise 객체를 직접 생성하는 코드를 작성해야한다

# 이미 상태가 결정된 Promise 객체
* 어떤 비동기 작업을 처리할 필요가 있다면, new 생성자와 executor 함수를 사용해서 Promise 객체를 만들어야 하지만, 그렇지 않고 바로 상태가 이미 결정된 Promise 객체를 만들고 싶을 때는 이 resolve 또는 reject 메소드를 사용한다.
# 이미 상태가 결정된 Promise 객체
## fulfilled 상태의 Promise 객체 만들기
```javascript
const p = Promise.resolve('success');
```
## rejected 상태의 Promise 객체 만들기
```javascript
const p = Promise.reject(new Error('fail'));
```

# 여러 Promise 객체를 다루는 방법
## all 메소드
* all 메소드도 then 메소드처럼 새로운 Promise 객체를 리턴
* 여러 Promise 객체의 작업 성공 결과를 기다렸다가 모두 한 번에 취합하기 위해서 사용
* 배열 안에 있는 모든 Promise 객체가 pending 상태에서 fulfilled 상태가 될 때까지 기다리고 모든 Promise 객체들이 fulfilled 상태가 되면, all 메소드가 리턴했던 Promise 객체는 fulfilled 상태가 되고, 각 Promise 객체의 작업 성공 결과들로 이루어진 배열을, 그 작업 성공 결과로 갖게된다.
* 객체들 중 하나라도, rejected 상태가 되면 all 메소드가 리턴한 Promise 객체는 rejected 상태가 되고 동일한 작업 실패 정보를 갖게 된다. 즉 하나의 Promise 객체라도 rejected 상태가 되면, 전체 작업이 실패한 것으로 간주해야 할 때 사용한다.
* 이렇게 Promise 객체가 하나라도 rejected 상태가 되는 경우에 대비하려면 이전에 배웠던 것처럼 catch 메소드를 붙여주면 된다.
```javascript
const p1 = fetch('https://learn.codeit.kr/api/members/1').then((res) => res.json());
const p2 = fetch('https://learn.codeit.kr/api/members/2').then((res) => res.json());
const p3 = fetch('https://learn.codeit.kr/api/members/3').then((res) => res.json());

Promise
  .all([p1, p2, p3])
  .then((results) => {
    console.log(results); // Array : [1번 직원 정보, 2번 직원 정보, 3번 직원 정보]
  });
  .catch((error) => {
    console.log(error);
  });
```
## race 메소드
* all 메소드와 마찬가지로 여러 Promise 객체들이 있는 배열을 아규먼트로 받는다.
* 아규먼트로 들어온 배열의 여러 Promise 객체들 중에서 가장 먼저 fulfilled 상태 또는 rejected 상태가 된 Promise 객체와 동일한 상태와 결과를 갖게된다.
```javascript
const p1 = new Promise((resolve, reject) => {
  setTimeout(() => resolve('Success'), 6000);
});
const p2 = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error('fail')), 2000);
});
const p3 = new Promise((resolve, reject) => {
  setTimeout(() => reject(new Error('fail2')), 4000);
});

Promise
  .race([p1, p2, p3])
  .then((result) => {
    console.log(result); // hello 출력
  })
  .catch((value) => {
    console.log(value);
  });
```
## allSettled 메소드
* 배열 내의 모든 Promise 객체가 fulfilled 또는 rejected 상태가 되기까지 기다리고, pending 상태의 Promise 객체가 하나도 없게 되면, A의 상태값은 fulfilled 상태가 되고 그 작업 성공 결과로, 하나의 배열을 갖게 된다.
* 배열에는 아규먼트로 받았던 배열 내의 각 promise 객체의 최종 상태를 status 프로퍼티, 그 작업 성공 결과는 value 프로퍼티, 그 작업 실패 정보는 reason 프로퍼티로 나타낸다.
```javascript
[
   {status: "fulfilled", value: 1},
   {status: "fulfilled", value: 2},
   {status: "fulfilled", value: 3},
   {status: "rejected",  reason: Error: an error}
]
```
## any 메소드
* 여러 Promise 객체들 중에서 가장 먼저 fulfilled 상태가 된 Promise 객체의 상태와 결과가 A에도 똑같이 반영된다.
* 만약 모든 Promise 객체가 rejected 상태가 되어버리면 AggregateError라고 하는 에러를 작업 실패 정보로 갖고 rejected 상태가 된다.



















